# Introduction to NumPy

NumPy (Numerical Python) is a fundamental library for numerical operations in Python. It provides efficient support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.
Benefits of using NumPy over standard Python lists:
NumPy arrays are more compact in memory and faster in execution.
NumPy provides a wide range of mathematical functions and operations optimized for scientific computing.
NumPy arrays can be easily integrated with other scientific computing libraries like SciPy and Matplotlib.
Installing NumPy


You can install NumPy using the Python package installer pip:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
print(np.__version__)

1.26.2


In [3]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a.shape)  

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)  

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)  

(5,)
(2, 3)
(2, 2, 2)


In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a.size) 

5


In [5]:
# Integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype) 

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)  

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)  

# Boolean array
d = np.array([True, False, True])
print(d.dtype)  

int32
float64
complex128
bool


In [6]:
# Create an array with float32 data type
a = np.array([1, 2, 3], dtype=np.float32)
print(a)        
print(a.dtype) 

[1. 2. 3.]
float32


In [7]:
# Create an array with int16 data type
b = np.array([1, 2, 3], dtype=np.int16)
print(b)        
print(b.dtype)  

[1 2 3]
int16


In [8]:
# From a list
a = np.array([1, 2, 3, 4, 5])
print(a)  

[1 2 3 4 5]


In [9]:
# From a list
c = [1, 2, 3, 4, 5]
a = np.asarray(c)
print(a)  

[1 2 3 4 5]


In [10]:
# From a tuple
d = (10, 20, 30)
b = np.asarray(d)
print(b)  

[10 20 30]


In [11]:
# Create a 1D array of ones
a = np.ones(5)
print(a)  

[1. 1. 1. 1. 1.]


In [12]:
# Create a 2D array of ones with shape (3, 4)
b = np.ones((3, 4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Create a 1D array of zeros
a = np.zeros(5)
print(a)  

[0. 0. 0. 0. 0.]


In [14]:
# Create a 2D array of zeros with shape (2, 3)
b = np.zeros((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Create an uninitialized 1D array
a = np.empty(5)
print(a)

[0. 0. 0. 0. 0.]


In [16]:
# Create an uninitialized 2D array with shape (2, 3)
b = np.empty((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Create a sequence from 0 to 9
a = np.arange(10)
print(a)  

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# Create a sequence from 2 to 10 with step size 2
b = np.arange(2, 11, 2)
print(b)  

[ 2  4  6  8 10]


In [19]:
# Create an array with 5 evenly spaced values between 0 and 1
a = np.linspace(0, 1, 5)
print(a) 

[0.   0.25 0.5  0.75 1.  ]


In [20]:
# Create an array with 9 evenly spaced values between 0 and 10
b = np.linspace(0, 10, 9)
print(b)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [21]:
# Create a 2x2 identity matrix
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [22]:
# Create a 3x3 identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 1. Basic Array Operations

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
print(c)  

[ 4 10 18]


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = b / a
print(c)  

[4.  2.5 2. ]


In [26]:
a = np.array([1, 2, 3])

b = a * 2
print(b)  

c = a / 2
print(c) 

[2 4 6]
[0.5 1.  1.5]


In [27]:
a = np.array([1, 4, 9])

b = np.sqrt(a)
print(b) 

[1. 2. 3.]


In [28]:
a = np.array([1, 2, 3])

b = np.exp(a)
print(b) 

[ 2.71828183  7.3890561  20.08553692]


In [29]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a[0])  
print(a[3])  

1
4


In [30]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 0])  
print(b[2, 1])  

1
8


In [31]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(a[indices])

[1 3 5]


In [32]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([0, 2])
print(b[rows, cols])

[1 9]


In [33]:
a = np.array([1, 2, 3, 4, 5])
print(a[a > 3])

[4 5]


In [34]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[b > 5]) 

[6 7 8 9]


In [35]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:6])  
print(a[:4])   
print(a[5:])   
print(a[::2])
print(a[::-1]) 

[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [36]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0:2, 0:2])  
print(b[:, 1])      
print(b[1:, :2])    

[[1 2]
 [4 5]]
[2 5 8]
[[4 5]
 [7 8]]


In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)  

# Reshape to a 2D array
b = a.reshape(2, 3)
print(b)

# Reshape to a 3D array
c = a.reshape(2, 1, 3)
print(c)

(6,)
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along a new axis (stacking)
c = np.stack((a, b))
print(c)

# Concatenate along an existing axis (horizontal)
d = np.concatenate((a, b), axis=None)
print(d)  

# Concatenate along an existing axis (vertical)
e = np.array([[1, 2], [3, 4]])
f = np.array([[5, 6], [7, 8]])
g = np.concatenate((e, f), axis=0)
print(g)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [39]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack arrays horizontally
c = np.hstack((a, b))
print(c)

# Stack arrays vertically
d = np.vstack((a, b))
print(d)

# Stack arrays along a new axis
e = np.stack((a, b), axis=1)
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [40]:
# Create a 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Split the array horizontally into 2 sub-arrays
left, right = np.hsplit(a, 2)
print("Horizontal split:")
print("Left sub-array:\n", left)
print("Right sub-array:\n", right)

Horizontal split:
Left sub-array:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Right sub-array:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [41]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)  

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [42]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [10, 20])
print(b) 

c = np.array([[1, 2], [3, 4]])
d = np.insert(c, 1, [10, 20], axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


In [43]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [0, 2])
print(b) 

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.delete(c, 1, axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]
